// <auto-generated />
using System;
using InfinityFit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfinityFit.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260204010808_Vouchere")]
    partial class Vouchere
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InfinityFit.Models.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000000"),
                            DateOfCreation = new DateTime(2026, 2, 4, 3, 8, 7, 642, DateTimeKind.Local).AddTicks(9724),
                            Description = "You have created your account!",
                            Icon = "/images/welcome.png",
                            Name = "Welcome"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            DateOfCreation = new DateTime(2026, 2, 4, 3, 8, 7, 642, DateTimeKind.Local).AddTicks(9791),
                            Description = "You posted for the first time",
                            Icon = "/images/post1.png",
                            Name = "First Post"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            DateOfCreation = new DateTime(2026, 2, 4, 3, 8, 7, 642, DateTimeKind.Local).AddTicks(9797),
                            Description = "You made 5 posts",
                            Icon = "/images/post5.png",
                            Name = "Traveler"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000020"),
                            DateOfCreation = new DateTime(2026, 2, 4, 3, 8, 7, 642, DateTimeKind.Local).AddTicks(9800),
                            Description = "You made 20 posts",
                            Icon = "/images/post20.png",
                            Name = "Explorer"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000050"),
                            DateOfCreation = new DateTime(2026, 2, 4, 3, 8, 7, 642, DateTimeKind.Local).AddTicks(9815),
                            Description = "You made 50 posts",
                            Icon = "/images/post50.png",
                            Name = "Adventurer"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000100"),
                            DateOfCreation = new DateTime(2026, 2, 4, 3, 8, 7, 642, DateTimeKind.Local).AddTicks(9818),
                            Description = "You made 100 posts",
                            Icon = "/images/post100.png",
                            Name = "Storyteller"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000250"),
                            DateOfCreation = new DateTime(2026, 2, 4, 3, 8, 7, 642, DateTimeKind.Local).AddTicks(9822),
                            Description = "You made 250 posts",
                            Icon = "/images/post250.png",
                            Name = "Content Creator"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000500"),
                            DateOfCreation = new DateTime(2026, 2, 4, 3, 8, 7, 642, DateTimeKind.Local).AddTicks(9825),
                            Description = "You made 500 posts",
                            Icon = "/images/post500.png",
                            Name = "Master Explorer"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000001000"),
                            DateOfCreation = new DateTime(2026, 2, 4, 3, 8, 7, 642, DateTimeKind.Local).AddTicks(9829),
                            Description = "You made 1,000 posts",
                            Icon = "/images/post1000.png",
                            Name = "Legendary Poster"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            DateOfCreation = new DateTime(2026, 2, 4, 3, 8, 7, 642, DateTimeKind.Local).AddTicks(9833),
                            Description = "Reached level 5",
                            Icon = "/images/level5.png",
                            Name = "Getting Started"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            DateOfCreation = new DateTime(2026, 2, 4, 3, 8, 7, 642, DateTimeKind.Local).AddTicks(9836),
                            Description = "Reached level 10",
                            Icon = "/images/level10.png",
                            Name = "Rising Star"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000020"),
                            DateOfCreation = new DateTime(2026, 2, 4, 3, 8, 7, 642, DateTimeKind.Local).AddTicks(9838),
                            Description = "Reached level 20",
                            Icon = "/images/level20.png",
                            Name = "Challenger"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000050"),
                            DateOfCreation = new DateTime(2026, 2, 4, 3, 8, 7, 642, DateTimeKind.Local).AddTicks(9844),
                            Description = "Reached level 50",
                            Icon = "/images/level50.png",
                            Name = "Veteran Explorer"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000100"),
                            DateOfCreation = new DateTime(2026, 2, 4, 3, 8, 7, 642, DateTimeKind.Local).AddTicks(9847),
                            Description = "Reached level 100",
                            Icon = "/images/level100.png",
                            Name = "Legend of InfinityFit"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            DateOfCreation = new DateTime(2026, 2, 4, 3, 8, 7, 642, DateTimeKind.Local).AddTicks(9851),
                            Description = "Gave your first like",
                            Icon = "/images/like1.png",
                            Name = "First Love"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000010"),
                            DateOfCreation = new DateTime(2026, 2, 4, 3, 8, 7, 642, DateTimeKind.Local).AddTicks(9854),
                            Description = "Gave 10 likes",
                            Icon = "/images/like10.png",
                            Name = "Supporter"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000050"),
                            DateOfCreation = new DateTime(2026, 2, 4, 3, 8, 7, 642, DateTimeKind.Local).AddTicks(9857),
                            Description = "Gave 50 likes",
                            Icon = "/images/like50.png",
                            Name = "Positive Vibes"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000100"),
                            DateOfCreation = new DateTime(2026, 2, 4, 3, 8, 7, 642, DateTimeKind.Local).AddTicks(9859),
                            Description = "Gave 100 likes",
                            Icon = "/images/like100.png",
                            Name = "Community Booster"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000500"),
                            DateOfCreation = new DateTime(2026, 2, 4, 3, 8, 7, 642, DateTimeKind.Local).AddTicks(9862),
                            Description = "Gave 500 likes",
                            Icon = "/images/like500.png",
                            Name = "Influencer"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000001000"),
                            DateOfCreation = new DateTime(2026, 2, 4, 3, 8, 7, 642, DateTimeKind.Local).AddTicks(9864),
                            Description = "Gave 1,000 likes",
                            Icon = "/images/like1000.png",
                            Name = "Social Machine"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000005000"),
                            DateOfCreation = new DateTime(2026, 2, 4, 3, 8, 7, 642, DateTimeKind.Local).AddTicks(9868),
                            Description = "Gave 5,000 likes",
                            Icon = "/images/like5000.png",
                            Name = "Infinity Reactor"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            DateOfCreation = new DateTime(2026, 2, 4, 3, 8, 7, 642, DateTimeKind.Local).AddTicks(9871),
                            Description = "Posted your first comment",
                            Icon = "/images/comment1.png",
                            Name = "First Words"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            DateOfCreation = new DateTime(2026, 2, 4, 3, 8, 7, 642, DateTimeKind.Local).AddTicks(9873),
                            Description = "Posted 5 comments",
                            Icon = "/images/comment5.png",
                            Name = "Conversationalist"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000015"),
                            DateOfCreation = new DateTime(2026, 2, 4, 3, 8, 7, 642, DateTimeKind.Local).AddTicks(9876),
                            Description = "Posted 15 comments",
                            Icon = "/images/comment15.png",
                            Name = "Active Voice"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000050"),
                            DateOfCreation = new DateTime(2026, 2, 4, 3, 8, 7, 642, DateTimeKind.Local).AddTicks(9936),
                            Description = "Posted 50 comments",
                            Icon = "/images/comment50.png",
                            Name = "Discussion Leader"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000100"),
                            DateOfCreation = new DateTime(2026, 2, 4, 3, 8, 7, 642, DateTimeKind.Local).AddTicks(9940),
                            Description = "Posted 100 comments",
                            Icon = "/images/comment100.png",
                            Name = "Community Speaker"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000250"),
                            DateOfCreation = new DateTime(2026, 2, 4, 3, 8, 7, 642, DateTimeKind.Local).AddTicks(9942),
                            Description = "Posted 250 comments",
                            Icon = "/images/comment250.png",
                            Name = "Debater Pro"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000500"),
                            DateOfCreation = new DateTime(2026, 2, 4, 3, 8, 7, 642, DateTimeKind.Local).AddTicks(9945),
                            Description = "Posted 500 comments",
                            Icon = "/images/comment500.png",
                            Name = "Social Anchor"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000001000"),
                            DateOfCreation = new DateTime(2026, 2, 4, 3, 8, 7, 642, DateTimeKind.Local).AddTicks(9949),
                            Description = "Posted 1,000 comments",
                            Icon = "/images/comment1000.png",
                            Name = "Voice of Infinity"
                        });
                });

            modelBuilder.Entity("InfinityFit.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("InfinityFit.Models.DailyLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DailyLocations");
                });

            modelBuilder.Entity("InfinityFit.Models.DailyQuizPlay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PlayDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DailyQuizPlays");
                });

            modelBuilder.Entity("InfinityFit.Models.DailySpinPlay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("PlayDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PointsWon")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DailySpinPlays");
                });

            modelBuilder.Entity("InfinityFit.Models.LeaderboardEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Engagement")
                        .HasColumnType("int");

                    b.Property<DateTime>("Month")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LeaderboardEntries");
                });

            modelBuilder.Entity("InfinityFit.Models.Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId", "PostId")
                        .IsUnique();

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("InfinityFit.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("InfinityFit.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Daily_Distance_Goal")
                        .HasColumnType("real");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLevelUp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("InfinityFit.Models.UserBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAwarded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserBadges");
                });

            modelBuilder.Entity("InfinityFit.Models.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Vouchers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "5E8EC987",
                            Description = "Reducere de 10% la intrarea la muzeu",
                            Name = "10% Reducere Muzeu"
                        },
                        new
                        {
                            Id = 2,
                            Code = "B0A7F515",
                            Description = "Reducere de 15% la un landmark turistic",
                            Name = "15% Reducere Landmark"
                        },
                        new
                        {
                            Id = 3,
                            Code = "B75BEA4C",
                            Description = "Reducere de 20% la restaurantul partener",
                            Name = "20% Reducere Restaurant"
                        },
                        new
                        {
                            Id = 4,
                            Code = "AACC17C7",
                            Description = "Reducere de 25% la turul ghidat al orașului",
                            Name = "25% Reducere Tur"
                        },
                        new
                        {
                            Id = 5,
                            Code = "7368632B",
                            Description = "Reducere de 30% la parcul de aventură",
                            Name = "30% Reducere Adventure Park"
                        },
                        new
                        {
                            Id = 6,
                            Code = "68CF069D",
                            Description = "Reducere de 35% la parcul de aventură",
                            Name = "35% Reducere Adventure Park"
                        },
                        new
                        {
                            Id = 7,
                            Code = "78855E9A",
                            Description = "Reducere de 40% la o cazare parteneră",
                            Name = "40% Reducere Cazare"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("InfinityFit.Models.Comment", b =>
                {
                    b.HasOne("InfinityFit.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InfinityFit.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InfinityFit.Models.DailyLocation", b =>
                {
                    b.HasOne("InfinityFit.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InfinityFit.Models.DailyQuizPlay", b =>
                {
                    b.HasOne("InfinityFit.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InfinityFit.Models.DailySpinPlay", b =>
                {
                    b.HasOne("InfinityFit.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InfinityFit.Models.LeaderboardEntry", b =>
                {
                    b.HasOne("InfinityFit.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InfinityFit.Models.Like", b =>
                {
                    b.HasOne("InfinityFit.Models.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InfinityFit.Models.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InfinityFit.Models.Post", b =>
                {
                    b.HasOne("InfinityFit.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InfinityFit.Models.UserBadge", b =>
                {
                    b.HasOne("InfinityFit.Models.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InfinityFit.Models.User", "User")
                        .WithMany("UserBadges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InfinityFit.Models.Voucher", b =>
                {
                    b.HasOne("InfinityFit.Models.User", "User")
                        .WithMany("Vouchers")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("InfinityFit.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("InfinityFit.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfinityFit.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("InfinityFit.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfinityFit.Models.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("InfinityFit.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("InfinityFit.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");

                    b.Navigation("Posts");

                    b.Navigation("UserBadges");

                    b.Navigation("Vouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
